---
name: "Run Todo to Issue"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  run:
    name: "Run Todo to Issue"
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          AUTO_ASSIGN: false
